---
name: CommandX 
version: 0.5.4
main: TN_Studios\CommandXV2\Main
api: 5.6.0
src-namespace-prefix: TN_Studios\CommandXV2
author: ThorNite Studios

commands:
    plugindev:
    description: Dev
    permission: "plugin.dev.command"
    permission-message: "Dev: §dThorNite Team§r, Mae, Malin"


permissions:
    plugin.dev.command:
    description: Please dont Activate that to a User!
    default: false
...
