---
name: CommandX
main: TN_Studios\CommandX\Main
src-namespace-prefix: TN_Studios\CommandX
api: 5.0.0
version: 1.3
description: CommandX
author: TN Studios
commands:
  cmd1:
    description: Command from Plugin (CommandX)
    permission: cmd1
    usage: "/cmd1"

  permissions: 
      cmd1:
      default: true
      description: Cmd1
...
