---
name: CommandX 
version: 5.6.0
main: TN_Studios\CommandX\Main
api: 5.0.0
src-namespace-prefix: TN_Studios\CommandX
author: ThorNite Studios

commands:
test:
    description: Test Command
    permission: "plugin.test.commandx"
    permission-message: "No Permission!"


permissions:
    plugin.test.commandx:
    description: A Permission
    default: op
...
