---
name: CommandX
main: TN_Studios\CommandX\Main
src-namespace-prefix: TN_Studios\CommandX
api: 5.0.0
version: 1.3.2
description: CommandX
author: TN Studios

commands:
   cmdx-spawn:
    description: Spawn Fake Player!
    permission: cmdx.spawn.fp

permissions:
    cmdx.spawn.fp:
       default: false
       description: Nothing
...
