---
name: CommandX
main: TN_Studios\CommandX\Main
src-namespace-prefix: TN_Studios\CommandX
api: 5.0.0
version: 1.3
description: CommandX
author: TN Studios

commands:
 cmd1:
   description: CommandX Plugin
   permission: commandx.cmd1

 cmdxreload:
   description: Reload CommandX Plugin
   permission: commandx.reload

permissions:
  commandx.cmd1:
  default: true
  description: Command 1 Permission

  commandx.reload:
  default: op 
  description: Reload Command Permission
...
