---
name: CommandX
main: TN_Studios\CommandX\Main
src-namespace-prefix: TN_Studios\CommandX
api: 5.0.0
version: 1.3
description: CommandX
author: TN Studios

commands:
 cmd1:
   description: CommandX Plugin
   permission: commandx.cmd1

permissions:
  commandx.cmd1:
  default: true
  description: Command 1 Permission
...
