---
name: CommandX
main: TN_Studios\CommandX\Main
src-namespace-prefix: TN_Studios\CommandX
api: 5.0.0
version: 1.2
description: CommandX
author: TN Studios
commands:
  test:
    description: Command from Plugin (CommandX)
...
