---
name: CommandX 
version: 5.6.0
main: TN_Studios\CommandXV2\Main
api: 5.0.0
src-namespace-prefix: TN_Studios\CommandXV2
author: ThorNite Studios

commands:
plugininfo:
    description: Plugin Info (CommandX)
    permission: "plugin.info.commandx"
    permission-message: "No Permission!"


permissions:
    plugin.info.commandx:
    description: A Permission
    default: op
...
