---
name: CommandX 
version: 0.5.3-BETA
main: TN_Studios\CommandXV2\Main
api: 5.0.0
src-namespace-prefix: TN_Studios\CommandXV2
author: ThorNite Studios

commands:
    pluginupdate:
    description: Update the Plugin!
    permission: "plugin.update.command"
    permission-message: "Please install it on https://github.com/Xgamer6/CommandX/Help/update.txt"


permissions:
    plugin.update.command:
    description: Please dont Activate that to a User!
    default: false
...
